const quotes = [
  { name: "Coding Freak", quote: "💪 Strength can be measured by estimation.\n Not courage." },
  { name: "Coding Freak", quote: "💡 Be strong, but not rude.\n Be kind, but not weak.\n Be bold, but don’t bully.\n Be humble, but not shy.\n Be proud, but not arrogant." },
  { name: "Coding Freak", quote: "😂 Code is like humor.\n When you have to explain it,\n it’s bad." },
  { name: "Coding Freak", quote: "🔧 Simplicity is the soul of efficiency." },
  { name: "Coding Freak", quote: "🛑 The best error message is the one that never shows up." },
  { name: "Coding Freak", quote: "🌊 A smooth sea never made a skilled programmer." },
  // { name: "Coding Freak", quote: "🧠 Think twice, code once." },
  // { name: "Coding Freak", quote: "🧩 First solve the problem. Then write the code." },
  // { name: "Coding Freak", quote: "🐞 Experience is the name everyone gives to their bugs." },
  // { name: "Coding Freak", quote: "🚀 Fail early, fail fast, learn always." },
  // { name: "Coding Freak", quote: "🕵️ Debugging is like being the detective in a crime movie where you are also the murderer." },
  // { name: "Coding Freak", quote: "📈 Small progress is still progress." },
  // { name: "Coding Freak", quote: "📚 Good code is its own best documentation." },
  // { name: "Coding Freak", quote: "🛠️ You don’t just write code, you craft solutions." },
  // { name: "Coding Freak", quote: "🔥 Don’t fear failure. Fear being in the exact same place next year." },
  // { name: "Coding Freak", quote: "🗺️ A goal without a plan is just a wish." },
  // { name: "Coding Freak", quote: "🎨 Coding is today's language of creativity." },
  // { name: "Coding Freak", quote: "🔮 The best way to predict the future is to invent it." },
  // { name: "Coding Freak", quote: "📖 Great developers never stop learning." },
  // { name: "Coding Freak", quote: "🧪 Keep calm and write tests." },
  // { name: "Coding Freak", quote: "🧭 Logic will get you from A to B. Creativity will get you everywhere." },
  // { name: "Coding Freak", quote: "✍️ Code like a poet, test like a scientist." },
  // { name: "Coding Freak", quote: "🔇 The quieter you become, the more you can hear your logic." },
  // { name: "Coding Freak", quote: "💻 Software is a reflection of the people who built it." },
  // { name: "Coding Freak", quote: "🔧 Even the best code is a work in progress." },
  // { name: "Coding Freak", quote: "🎨 A line of code is like a brushstroke on a canvas." },
  // { name: "Coding Freak", quote: "🧠 If it works, don’t mess with it. If it doesn’t, understand it." },
  // { name: "Coding Freak", quote: "🧼 A function a day keeps spaghetti code away." },
  // { name: "Coding Freak", quote: "✏️ Don’t comment bad code — rewrite it." },
  // { name: "Coding Freak", quote: "🤝 In code we trust. In tests we believe." },
  // { name: "Coding Freak", quote: "⚖️ A great coder knows when to say 'no' to complexity." },
  // { name: "Coding Freak", quote: "📖 Your code is a story — make it readable." },
  // { name: "Coding Freak", quote: "🐛 One commit at a time. One bug less at a time." },
  // { name: "Coding Freak", quote: "🛠️ Build things you wish existed." },
  // { name: "Coding Freak", quote: "📤 Comfort is the enemy of growth." },
  // { name: "Coding Freak", quote: "🐞 Every bug is a chance to learn something new." },
  // { name: "Coding Freak", quote: "🔁 Patience, persistence, and practice — the coder’s trinity." },
  // { name: "Coding Freak", quote: "🚧 You’re not stuck, you’re just early in the process." },
  // { name: "Coding Freak", quote: "🔄 A reboot is not always a bad thing — in code or life." },
  // { name: "Coding Freak", quote: "🏗️ Your first 100 programs will suck. Do them anyway." },
  // { name: "Coding Freak", quote: "🎯 Elegance in code is the result of restraint, not abundance." },
  // { name: "Coding Freak", quote: "🧙‍♂️ A wise programmer listens to warnings." },
  // { name: "Coding Freak", quote: "👨‍💻 Write code for humans first, then for machines." },
  // { name: "Coding Freak", quote: "🧠 Stay curious. Stay coding." },
  // { name: "Coding Freak", quote: "🏁 Great code starts with great habits." },
  // { name: "Coding Freak", quote: "🎢 You only fail when you stop trying." },
  // { name: "Coding Freak", quote: "🔍 The best debugging tool is a fresh pair of eyes." },
  // { name: "Coding Freak", quote: "🧘‍♂️ Code with purpose. Debug with focus." },
  // { name: "Coding Freak", quote: "💾 There’s no such thing as too many backups." }
];

module.exports = quotes;
